-- ============================================================
--  CRMP - Complaints & Requests Management Portal
--  01_schema.sql  |  Oracle DDL
--  Run as the schema owner (e.g., CRMP_OWNER)
-- ============================================================

-- ----------------------------------------------------------------
-- 1. REFERENCE / LOOKUP TABLES
-- ----------------------------------------------------------------

CREATE TABLE DIVISIONS (
    DIVISION_ID         NUMBER(10)      NOT NULL,
    DIVISION_NAME       VARCHAR2(200)   NOT NULL,
    DIVISION_CODE       VARCHAR2(20)    NOT NULL,
    PARENT_DIVISION_ID  NUMBER(10),
    IS_ACTIVE           NUMBER(1)       DEFAULT 1 NOT NULL,
    CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_DIVISIONS PRIMARY KEY (DIVISION_ID),
    CONSTRAINT UQ_DIV_CODE UNIQUE (DIVISION_CODE),
    CONSTRAINT FK_DIV_PARENT FOREIGN KEY (PARENT_DIVISION_ID) REFERENCES DIVISIONS(DIVISION_ID)
);

CREATE TABLE BUILDINGS (
    BUILDING_ID     NUMBER(10)      NOT NULL,
    BUILDING_NAME   VARCHAR2(200)   NOT NULL,
    BUILDING_CODE   VARCHAR2(20)    NOT NULL,
    IS_ACTIVE       NUMBER(1)       DEFAULT 1 NOT NULL,
    CONSTRAINT PK_BUILDINGS PRIMARY KEY (BUILDING_ID),
    CONSTRAINT UQ_BLDG_CODE UNIQUE (BUILDING_CODE)
);

CREATE TABLE ROLES (
    ROLE_ID     NUMBER(10)      NOT NULL,
    ROLE_CODE   VARCHAR2(50)    NOT NULL,
    ROLE_NAME   VARCHAR2(100)   NOT NULL,
    DESCRIPTION VARCHAR2(500),
    SORT_ORDER  NUMBER(5)       DEFAULT 0,
    CONSTRAINT PK_ROLES PRIMARY KEY (ROLE_ID),
    CONSTRAINT UQ_ROLE_CODE UNIQUE (ROLE_CODE)
);

-- ----------------------------------------------------------------
-- 2. USERS
-- ----------------------------------------------------------------

CREATE TABLE USERS (
    USER_ID         NUMBER(10)      NOT NULL,
    USERNAME        VARCHAR2(100)   NOT NULL,
    PASSWORD_HASH   VARCHAR2(256),
    FULL_NAME       VARCHAR2(200)   NOT NULL,
    EMAIL           VARCHAR2(254)   NOT NULL,
    PHONE           VARCHAR2(30),
    DIVISION_ID     NUMBER(10)      NOT NULL,
    DESIGNATION     VARCHAR2(200),
    BUILDING_ID     NUMBER(10),
    FLOOR_NUMBER    VARCHAR2(20),
    IS_ACTIVE       NUMBER(1)       DEFAULT 1 NOT NULL,
    LAST_LOGIN_AT   TIMESTAMP,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_USERS PRIMARY KEY (USER_ID),
    CONSTRAINT UQ_USERNAME UNIQUE (USERNAME),
    CONSTRAINT UQ_EMAIL UNIQUE (EMAIL),
    CONSTRAINT FK_USERS_DIVISION FOREIGN KEY (DIVISION_ID) REFERENCES DIVISIONS(DIVISION_ID),
    CONSTRAINT FK_USERS_BUILDING FOREIGN KEY (BUILDING_ID) REFERENCES BUILDINGS(BUILDING_ID)
);

CREATE TABLE USER_ROLES (
    USER_ROLE_ID    NUMBER(10)  NOT NULL,
    USER_ID         NUMBER(10)  NOT NULL,
    ROLE_ID         NUMBER(10)  NOT NULL,
    DIVISION_ID     NUMBER(10),
    GRANTED_BY      NUMBER(10)  NOT NULL,
    GRANTED_AT      TIMESTAMP   DEFAULT SYSTIMESTAMP NOT NULL,
    IS_ACTIVE       NUMBER(1)   DEFAULT 1 NOT NULL,
    CONSTRAINT PK_USER_ROLES PRIMARY KEY (USER_ROLE_ID),
    CONSTRAINT FK_UR_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT FK_UR_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ROLE_ID),
    CONSTRAINT FK_UR_DIVISION FOREIGN KEY (DIVISION_ID) REFERENCES DIVISIONS(DIVISION_ID),
    CONSTRAINT FK_UR_GRANTED_BY FOREIGN KEY (GRANTED_BY) REFERENCES USERS(USER_ID)
);

CREATE TABLE ROLE_DELEGATIONS (
    DELEGATION_ID       NUMBER(10)      NOT NULL,
    DELEGATOR_USER_ID   NUMBER(10)      NOT NULL,
    DELEGATEE_USER_ID   NUMBER(10)      NOT NULL,
    ROLE_ID             NUMBER(10)      NOT NULL,
    DIVISION_ID         NUMBER(10),
    START_DATE          DATE            NOT NULL,
    END_DATE            DATE            NOT NULL,
    REASON              VARCHAR2(500)   NOT NULL,
    CREATED_BY          NUMBER(10)      NOT NULL,
    CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    IS_ACTIVE           NUMBER(1)       DEFAULT 1 NOT NULL,
    CONSTRAINT PK_DELEGATIONS PRIMARY KEY (DELEGATION_ID),
    CONSTRAINT FK_DEL_DELEGATOR FOREIGN KEY (DELEGATOR_USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT FK_DEL_DELEGATEE FOREIGN KEY (DELEGATEE_USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT FK_DEL_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ROLE_ID),
    CONSTRAINT FK_DEL_DIVISION FOREIGN KEY (DIVISION_ID) REFERENCES DIVISIONS(DIVISION_ID),
    CONSTRAINT CK_DEL_DATES CHECK (END_DATE >= START_DATE)
);

-- ----------------------------------------------------------------
-- 3. SERVICE CATALOG
-- ----------------------------------------------------------------

CREATE TABLE SERVICE_CATEGORIES (
    CATEGORY_ID     NUMBER(10)      NOT NULL,
    CATEGORY_NAME   VARCHAR2(200)   NOT NULL,
    CATEGORY_CODE   VARCHAR2(50)    NOT NULL,
    DESCRIPTION     VARCHAR2(1000),
    ICON_CLASS      VARCHAR2(100)   DEFAULT 'icon-folder',
    COLOR_HEX       VARCHAR2(10)    DEFAULT '#4F46E5',
    SORT_ORDER      NUMBER(5)       DEFAULT 0,
    IS_ACTIVE       NUMBER(1)       DEFAULT 1 NOT NULL,
    CONSTRAINT PK_CATEGORIES PRIMARY KEY (CATEGORY_ID),
    CONSTRAINT UQ_CAT_CODE UNIQUE (CATEGORY_CODE)
);

CREATE TABLE MODERATOR_CATEGORIES (
    MOD_CAT_ID      NUMBER(10)  NOT NULL,
    USER_ID         NUMBER(10)  NOT NULL,
    CATEGORY_ID     NUMBER(10)  NOT NULL,
    ASSIGNED_BY     NUMBER(10)  NOT NULL,
    ASSIGNED_AT     TIMESTAMP   DEFAULT SYSTIMESTAMP NOT NULL,
    IS_ACTIVE       NUMBER(1)   DEFAULT 1 NOT NULL,
    CONSTRAINT PK_MOD_CATS PRIMARY KEY (MOD_CAT_ID),
    CONSTRAINT FK_MC_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT FK_MC_CAT FOREIGN KEY (CATEGORY_ID) REFERENCES SERVICE_CATEGORIES(CATEGORY_ID),
    CONSTRAINT FK_MC_ASSIGNED_BY FOREIGN KEY (ASSIGNED_BY) REFERENCES USERS(USER_ID)
);

CREATE TABLE TECH_EXPERT_CATEGORIES (
    TE_CAT_ID       NUMBER(10)  NOT NULL,
    USER_ID         NUMBER(10)  NOT NULL,
    CATEGORY_ID     NUMBER(10)  NOT NULL,
    ASSIGNED_BY     NUMBER(10)  NOT NULL,
    ASSIGNED_AT     TIMESTAMP   DEFAULT SYSTIMESTAMP NOT NULL,
    IS_ACTIVE       NUMBER(1)   DEFAULT 1 NOT NULL,
    CONSTRAINT PK_TE_CATS PRIMARY KEY (TE_CAT_ID),
    CONSTRAINT FK_TC_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT FK_TC_CAT FOREIGN KEY (CATEGORY_ID) REFERENCES SERVICE_CATEGORIES(CATEGORY_ID),
    CONSTRAINT FK_TC_ASSIGNED_BY FOREIGN KEY (ASSIGNED_BY) REFERENCES USERS(USER_ID)
);

-- ----------------------------------------------------------------
-- 4. WORKFLOW ENGINE
-- ----------------------------------------------------------------

CREATE TABLE WORKFLOWS (
    WORKFLOW_ID     NUMBER(10)      NOT NULL,
    WORKFLOW_NAME   VARCHAR2(200)   NOT NULL,
    DESCRIPTION     VARCHAR2(500),
    IS_ACTIVE       NUMBER(1)       DEFAULT 1 NOT NULL,
    CREATED_BY      NUMBER(10),
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_WORKFLOWS PRIMARY KEY (WORKFLOW_ID)
);

CREATE TABLE WORKFLOW_STAGES (
    STAGE_ID                NUMBER(10)      NOT NULL,
    WORKFLOW_ID             NUMBER(10)      NOT NULL,
    STAGE_ORDER             NUMBER(5)       NOT NULL,
    STAGE_NAME              VARCHAR2(200)   NOT NULL,
    ROLE_ID                 NUMBER(10)      NOT NULL,
    IS_CONFIRMATION_ONLY    NUMBER(1)       DEFAULT 0 NOT NULL,
    REMARKS_REQUIRED        NUMBER(1)       DEFAULT 0 NOT NULL,
    IS_ACTIVE               NUMBER(1)       DEFAULT 1 NOT NULL,
    CONSTRAINT PK_WF_STAGES PRIMARY KEY (STAGE_ID),
    CONSTRAINT FK_WFS_WORKFLOW FOREIGN KEY (WORKFLOW_ID) REFERENCES WORKFLOWS(WORKFLOW_ID),
    CONSTRAINT FK_WFS_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ROLE_ID),
    CONSTRAINT UQ_WF_STAGE_ORDER UNIQUE (WORKFLOW_ID, STAGE_ORDER)
);

-- ----------------------------------------------------------------
-- 5. DYNAMIC FORM BUILDER
-- ----------------------------------------------------------------

CREATE TABLE OPTION_LISTS (
    LIST_ID         NUMBER(10)      NOT NULL,
    LIST_NAME       VARCHAR2(200)   NOT NULL,
    LIST_CODE       VARCHAR2(100)   NOT NULL,
    DESCRIPTION     VARCHAR2(500),
    CREATED_BY      NUMBER(10),
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_OPTION_LISTS PRIMARY KEY (LIST_ID),
    CONSTRAINT UQ_LIST_CODE UNIQUE (LIST_CODE)
);

CREATE TABLE OPTION_LIST_VALUES (
    VALUE_ID        NUMBER(10)      NOT NULL,
    LIST_ID         NUMBER(10)      NOT NULL,
    VALUE_TEXT      VARCHAR2(500)   NOT NULL,
    VALUE_CODE      VARCHAR2(100)   NOT NULL,
    SORT_ORDER      NUMBER(5)       DEFAULT 0,
    IS_ACTIVE       NUMBER(1)       DEFAULT 1 NOT NULL,
    CONSTRAINT PK_OLV PRIMARY KEY (VALUE_ID),
    CONSTRAINT FK_OLV_LIST FOREIGN KEY (LIST_ID) REFERENCES OPTION_LISTS(LIST_ID)
);

CREATE TABLE REQUEST_TYPES (
    TYPE_ID         NUMBER(10)      NOT NULL,
    CATEGORY_ID     NUMBER(10)      NOT NULL,
    TYPE_NAME       VARCHAR2(200)   NOT NULL,
    TYPE_CODE       VARCHAR2(100)   NOT NULL,
    DESCRIPTION     VARCHAR2(1000),
    SLA_HOURS       NUMBER(10)      DEFAULT 72 NOT NULL,
    WORKFLOW_ID     NUMBER(10),
    ICON_CLASS      VARCHAR2(100)   DEFAULT 'icon-ticket',
    IS_ACTIVE       NUMBER(1)       DEFAULT 1 NOT NULL,
    IS_CONNECTION_TYPE NUMBER(1)    DEFAULT 0 NOT NULL,
    CREATED_BY      NUMBER(10),
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_REQUEST_TYPES PRIMARY KEY (TYPE_ID),
    CONSTRAINT UQ_TYPE_CODE UNIQUE (TYPE_CODE),
    CONSTRAINT FK_RT_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES SERVICE_CATEGORIES(CATEGORY_ID),
    CONSTRAINT FK_RT_WORKFLOW FOREIGN KEY (WORKFLOW_ID) REFERENCES WORKFLOWS(WORKFLOW_ID)
);

CREATE TABLE FORM_FIELDS (
    FIELD_ID                    NUMBER(10)      NOT NULL,
    TYPE_ID                     NUMBER(10)      NOT NULL,
    FIELD_LABEL                 VARCHAR2(300)   NOT NULL,
    FIELD_NAME                  VARCHAR2(100)   NOT NULL,
    FIELD_TYPE                  VARCHAR2(30)    NOT NULL,
    IS_REQUIRED                 NUMBER(1)       DEFAULT 0 NOT NULL,
    SORT_ORDER                  NUMBER(5)       DEFAULT 0,
    PLACEHOLDER                 VARCHAR2(300),
    DEFAULT_VALUE               VARCHAR2(500),
    OPTION_LIST_ID              NUMBER(10),
    CONDITIONAL_PARENT_FIELD_ID NUMBER(10),
    CONDITIONAL_SHOW_WHEN_VALUE VARCHAR2(500),
    HELP_TEXT                   VARCHAR2(500),
    IS_ACTIVE                   NUMBER(1)       DEFAULT 1 NOT NULL,
    CONSTRAINT PK_FORM_FIELDS PRIMARY KEY (FIELD_ID),
    CONSTRAINT FK_FF_TYPE FOREIGN KEY (TYPE_ID) REFERENCES REQUEST_TYPES(TYPE_ID),
    CONSTRAINT FK_FF_OPTION_LIST FOREIGN KEY (OPTION_LIST_ID) REFERENCES OPTION_LISTS(LIST_ID),
    CONSTRAINT FK_FF_PARENT FOREIGN KEY (CONDITIONAL_PARENT_FIELD_ID) REFERENCES FORM_FIELDS(FIELD_ID),
    CONSTRAINT CK_FIELD_TYPE CHECK (FIELD_TYPE IN ('TEXT','TEXTAREA','NUMBER','DATE','DATETIME','DROPDOWN','CHECKBOX','RADIO','FILE','EMAIL','PHONE'))
);

-- ----------------------------------------------------------------
-- 6. REQUESTS
-- ----------------------------------------------------------------

CREATE TABLE REQUESTS (
    REQUEST_ID              NUMBER(10)      NOT NULL,
    REQUEST_NUMBER          VARCHAR2(30)    NOT NULL,
    TYPE_ID                 NUMBER(10)      NOT NULL,
    SUBMITTER_USER_ID       NUMBER(10)      NOT NULL,
    ON_BEHALF_OF_USER_ID    NUMBER(10),
    DIVISION_ID             NUMBER(10)      NOT NULL,
    STATUS                  VARCHAR2(30)    DEFAULT 'PENDING_APPROVAL' NOT NULL,
    CURRENT_STAGE_ID        NUMBER(10),
    TECH_EXPERT_ID          NUMBER(10),
    SUMMARY                 VARCHAR2(1000),
    PRIORITY                VARCHAR2(20)    DEFAULT 'NORMAL' NOT NULL,
    SLA_DEADLINE            TIMESTAMP,
    IS_SLA_BREACHED         NUMBER(1)       DEFAULT 0 NOT NULL,
    SLA_BREACH_NOTIFIED     NUMBER(1)       DEFAULT 0 NOT NULL,
    SLA_WARN_NOTIFIED       NUMBER(1)       DEFAULT 0 NOT NULL,
    SUBMITTED_AT            TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    RESOLVED_AT             TIMESTAMP,
    CLOSED_AT               TIMESTAMP,
    RESOLUTION_NOTES        CLOB,
    CREATED_AT              TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT              TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_REQUESTS PRIMARY KEY (REQUEST_ID),
    CONSTRAINT UQ_REQUEST_NUMBER UNIQUE (REQUEST_NUMBER),
    CONSTRAINT FK_REQ_TYPE FOREIGN KEY (TYPE_ID) REFERENCES REQUEST_TYPES(TYPE_ID),
    CONSTRAINT FK_REQ_SUBMITTER FOREIGN KEY (SUBMITTER_USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT FK_REQ_ONBEHALF FOREIGN KEY (ON_BEHALF_OF_USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT FK_REQ_DIVISION FOREIGN KEY (DIVISION_ID) REFERENCES DIVISIONS(DIVISION_ID),
    CONSTRAINT FK_REQ_STAGE FOREIGN KEY (CURRENT_STAGE_ID) REFERENCES WORKFLOW_STAGES(STAGE_ID),
    CONSTRAINT FK_REQ_TECH FOREIGN KEY (TECH_EXPERT_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT CK_REQ_STATUS CHECK (STATUS IN ('DRAFT','PENDING_APPROVAL','APPROVED','REJECTED','IN_PROGRESS','RESOLVED','CLOSED','CANCELLED')),
    CONSTRAINT CK_REQ_PRIORITY CHECK (PRIORITY IN ('LOW','NORMAL','HIGH','URGENT'))
);

CREATE TABLE REQUEST_FIELD_VALUES (
    VALUE_ID        NUMBER(10)  NOT NULL,
    REQUEST_ID      NUMBER(10)  NOT NULL,
    FIELD_ID        NUMBER(10)  NOT NULL,
    FIELD_VALUE     VARCHAR2(4000),
    FIELD_VALUE_CLOB CLOB,
    CONSTRAINT PK_RFV PRIMARY KEY (VALUE_ID),
    CONSTRAINT FK_RFV_REQUEST FOREIGN KEY (REQUEST_ID) REFERENCES REQUESTS(REQUEST_ID),
    CONSTRAINT FK_RFV_FIELD FOREIGN KEY (FIELD_ID) REFERENCES FORM_FIELDS(FIELD_ID)
);

CREATE TABLE REQUEST_ATTACHMENTS (
    ATTACHMENT_ID   NUMBER(10)      NOT NULL,
    REQUEST_ID      NUMBER(10)      NOT NULL,
    FILE_NAME       VARCHAR2(500)   NOT NULL,
    FILE_PATH       VARCHAR2(1000)  NOT NULL,
    FILE_SIZE       NUMBER(15),
    MIME_TYPE       VARCHAR2(200),
    UPLOADED_BY     NUMBER(10)      NOT NULL,
    UPLOADED_AT     TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ATTACHMENTS PRIMARY KEY (ATTACHMENT_ID),
    CONSTRAINT FK_ATT_REQUEST FOREIGN KEY (REQUEST_ID) REFERENCES REQUESTS(REQUEST_ID),
    CONSTRAINT FK_ATT_UPLOADER FOREIGN KEY (UPLOADED_BY) REFERENCES USERS(USER_ID)
);

-- ----------------------------------------------------------------
-- 7. APPROVAL TRACKING
-- ----------------------------------------------------------------

CREATE TABLE REQUEST_APPROVALS (
    APPROVAL_ID         NUMBER(10)      NOT NULL,
    REQUEST_ID          NUMBER(10)      NOT NULL,
    STAGE_ID            NUMBER(10)      NOT NULL,
    APPROVER_USER_ID    NUMBER(10)      NOT NULL,
    DELEGATED_BY_USER_ID NUMBER(10),
    ACTION              VARCHAR2(30)    DEFAULT 'PENDING' NOT NULL,
    REMARKS             VARCHAR2(2000),
    IS_CONFIRMED        NUMBER(1)       DEFAULT 0,
    ACTIONED_AT         TIMESTAMP,
    SEQUENCE_NUMBER     NUMBER(5)       NOT NULL,
    CONSTRAINT PK_APPROVALS PRIMARY KEY (APPROVAL_ID),
    CONSTRAINT FK_APR_REQUEST FOREIGN KEY (REQUEST_ID) REFERENCES REQUESTS(REQUEST_ID),
    CONSTRAINT FK_APR_STAGE FOREIGN KEY (STAGE_ID) REFERENCES WORKFLOW_STAGES(STAGE_ID),
    CONSTRAINT FK_APR_APPROVER FOREIGN KEY (APPROVER_USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT FK_APR_DELEGATED FOREIGN KEY (DELEGATED_BY_USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT CK_APR_ACTION CHECK (ACTION IN ('PENDING','APPROVED','REJECTED','SKIPPED_AUTO','DELEGATED'))
);

CREATE TABLE REQUEST_TIMELINE (
    TIMELINE_ID     NUMBER(10)      NOT NULL,
    REQUEST_ID      NUMBER(10)      NOT NULL,
    EVENT_TYPE      VARCHAR2(50)    NOT NULL,
    EVENT_DESC      VARCHAR2(2000)  NOT NULL,
    PERFORMED_BY    NUMBER(10),
    PERFORMED_AT    TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    METADATA_JSON   CLOB,
    CONSTRAINT PK_TIMELINE PRIMARY KEY (TIMELINE_ID),
    CONSTRAINT FK_TL_REQUEST FOREIGN KEY (REQUEST_ID) REFERENCES REQUESTS(REQUEST_ID),
    CONSTRAINT FK_TL_USER FOREIGN KEY (PERFORMED_BY) REFERENCES USERS(USER_ID)
);

-- ----------------------------------------------------------------
-- 8. SLA CONFIGURATION
-- ----------------------------------------------------------------

CREATE TABLE SLA_CONFIGS (
    SLA_ID                      NUMBER(10)      NOT NULL,
    TYPE_ID                     NUMBER(10),
    CATEGORY_ID                 NUMBER(10),
    PRIORITY                    VARCHAR2(20)    DEFAULT 'NORMAL',
    SLA_HOURS                   NUMBER(10)      NOT NULL,
    WARN_THRESHOLD_PCT          NUMBER(5)       DEFAULT 75,
    BREACH_NOTIFY_ROLES         VARCHAR2(500),
    CONSTRAINT PK_SLA_CONFIGS PRIMARY KEY (SLA_ID),
    CONSTRAINT FK_SLA_TYPE FOREIGN KEY (TYPE_ID) REFERENCES REQUEST_TYPES(TYPE_ID),
    CONSTRAINT FK_SLA_CAT FOREIGN KEY (CATEGORY_ID) REFERENCES SERVICE_CATEGORIES(CATEGORY_ID)
);

-- ----------------------------------------------------------------
-- 9. CONNECTION DIRECTORY
-- ----------------------------------------------------------------

CREATE TABLE CONNECTIONS (
    CONN_ID             NUMBER(10)      NOT NULL,
    REQUEST_ID          NUMBER(10),
    USER_ID             NUMBER(10)      NOT NULL,
    DIVISION_ID         NUMBER(10)      NOT NULL,
    CONN_TYPE           VARCHAR2(100)   NOT NULL,
    CONN_IDENTIFIER     VARCHAR2(200),
    LOCATION_BUILDING_ID NUMBER(10),
    LOCATION_FLOOR      VARCHAR2(20),
    LOCATION_ROOM       VARCHAR2(50),
    NOTES               VARCHAR2(2000),
    IS_ACTIVE           NUMBER(1)       DEFAULT 1 NOT NULL,
    CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_CONNECTIONS PRIMARY KEY (CONN_ID),
    CONSTRAINT FK_CONN_REQUEST FOREIGN KEY (REQUEST_ID) REFERENCES REQUESTS(REQUEST_ID),
    CONSTRAINT FK_CONN_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT FK_CONN_DIVISION FOREIGN KEY (DIVISION_ID) REFERENCES DIVISIONS(DIVISION_ID),
    CONSTRAINT FK_CONN_BUILDING FOREIGN KEY (LOCATION_BUILDING_ID) REFERENCES BUILDINGS(BUILDING_ID)
);

-- ----------------------------------------------------------------
-- 10. NOTIFICATIONS
-- ----------------------------------------------------------------

CREATE TABLE NOTIFICATIONS (
    NOTIF_ID        NUMBER(10)      NOT NULL,
    USER_ID         NUMBER(10)      NOT NULL,
    TITLE           VARCHAR2(300)   NOT NULL,
    MESSAGE         VARCHAR2(2000)  NOT NULL,
    LINK            VARCHAR2(500),
    IS_READ         NUMBER(1)       DEFAULT 0 NOT NULL,
    NOTIF_TYPE      VARCHAR2(50)    NOT NULL,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_NOTIFS PRIMARY KEY (NOTIF_ID),
    CONSTRAINT FK_NOTIF_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE USER_NOTIFICATION_PREFS (
    PREF_ID         NUMBER(10)  NOT NULL,
    USER_ID         NUMBER(10)  NOT NULL,
    NOTIF_TYPE      VARCHAR2(50) NOT NULL,
    EMAIL_ENABLED   NUMBER(1)   DEFAULT 1 NOT NULL,
    INAPP_ENABLED   NUMBER(1)   DEFAULT 1 NOT NULL,
    CONSTRAINT PK_NOTIF_PREFS PRIMARY KEY (PREF_ID),
    CONSTRAINT FK_NP_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT UQ_NP_USER_TYPE UNIQUE (USER_ID, NOTIF_TYPE)
);

-- ----------------------------------------------------------------
-- 11. KNOWLEDGE BASE
-- ----------------------------------------------------------------

CREATE TABLE KB_ARTICLES (
    ARTICLE_ID      NUMBER(10)      NOT NULL,
    TITLE           VARCHAR2(500)   NOT NULL,
    CONTENT_HTML    CLOB,
    CATEGORY_ID     NUMBER(10),
    TYPE_ID         NUMBER(10),
    AUTHOR_ID       NUMBER(10)      NOT NULL,
    PUBLISHED_AT    TIMESTAMP,
    VIEW_COUNT      NUMBER(10)      DEFAULT 0,
    IS_PUBLISHED    NUMBER(1)       DEFAULT 0 NOT NULL,
    TAGS            VARCHAR2(500),
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_KB_ARTICLES PRIMARY KEY (ARTICLE_ID),
    CONSTRAINT FK_KB_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES SERVICE_CATEGORIES(CATEGORY_ID),
    CONSTRAINT FK_KB_TYPE FOREIGN KEY (TYPE_ID) REFERENCES REQUEST_TYPES(TYPE_ID),
    CONSTRAINT FK_KB_AUTHOR FOREIGN KEY (AUTHOR_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE KB_FEEDBACK (
    FEEDBACK_ID     NUMBER(10)  NOT NULL,
    ARTICLE_ID      NUMBER(10)  NOT NULL,
    USER_ID         NUMBER(10)  NOT NULL,
    IS_HELPFUL      NUMBER(1)   NOT NULL,
    COMMENT         VARCHAR2(1000),
    CREATED_AT      TIMESTAMP   DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_KB_FEEDBACK PRIMARY KEY (FEEDBACK_ID),
    CONSTRAINT FK_KBF_ARTICLE FOREIGN KEY (ARTICLE_ID) REFERENCES KB_ARTICLES(ARTICLE_ID),
    CONSTRAINT FK_KBF_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- ----------------------------------------------------------------
-- 12. POST-RESOLUTION RATINGS
-- ----------------------------------------------------------------

CREATE TABLE REQUEST_RATINGS (
    RATING_ID       NUMBER(10)      NOT NULL,
    REQUEST_ID      NUMBER(10)      NOT NULL,
    RATED_BY_USER_ID NUMBER(10)     NOT NULL,
    SCORE           NUMBER(1)       NOT NULL,
    COMMENT         VARCHAR2(1000),
    RATED_AT        TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_RATINGS PRIMARY KEY (RATING_ID),
    CONSTRAINT FK_RAT_REQUEST FOREIGN KEY (REQUEST_ID) REFERENCES REQUESTS(REQUEST_ID),
    CONSTRAINT FK_RAT_USER FOREIGN KEY (RATED_BY_USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT UQ_RAT_REQUEST UNIQUE (REQUEST_ID),
    CONSTRAINT CK_RAT_SCORE CHECK (SCORE BETWEEN 1 AND 5)
);

-- ----------------------------------------------------------------
-- 13. ANNOUNCEMENTS / STATUS BOARD
-- ----------------------------------------------------------------

CREATE TABLE ANNOUNCEMENTS (
    ANN_ID          NUMBER(10)      NOT NULL,
    TITLE           VARCHAR2(300)   NOT NULL,
    CONTENT         VARCHAR2(4000)  NOT NULL,
    SEVERITY        VARCHAR2(20)    DEFAULT 'INFO' NOT NULL,
    CATEGORY_ID     NUMBER(10),
    CREATED_BY      NUMBER(10)      NOT NULL,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    EXPIRES_AT      TIMESTAMP,
    IS_ACTIVE       NUMBER(1)       DEFAULT 1 NOT NULL,
    CONSTRAINT PK_ANNOUNCEMENTS PRIMARY KEY (ANN_ID),
    CONSTRAINT FK_ANN_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES SERVICE_CATEGORIES(CATEGORY_ID),
    CONSTRAINT FK_ANN_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USERS(USER_ID),
    CONSTRAINT CK_ANN_SEVERITY CHECK (SEVERITY IN ('INFO','WARNING','CRITICAL'))
);

-- ----------------------------------------------------------------
-- 14. REQUEST TEMPLATES
-- ----------------------------------------------------------------

CREATE TABLE REQUEST_TEMPLATES (
    TEMPLATE_ID         NUMBER(10)      NOT NULL,
    USER_ID             NUMBER(10)      NOT NULL,
    TYPE_ID             NUMBER(10)      NOT NULL,
    TEMPLATE_NAME       VARCHAR2(200)   NOT NULL,
    FIELD_VALUES_JSON   CLOB,
    IS_SHARED           NUMBER(1)       DEFAULT 0 NOT NULL,
    CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_TEMPLATES PRIMARY KEY (TEMPLATE_ID),
    CONSTRAINT FK_TPL_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT FK_TPL_TYPE FOREIGN KEY (TYPE_ID) REFERENCES REQUEST_TYPES(TYPE_ID)
);

-- ----------------------------------------------------------------
-- 15. SAVED REPORTS
-- ----------------------------------------------------------------

CREATE TABLE SAVED_REPORTS (
    REPORT_ID       NUMBER(10)      NOT NULL,
    REPORT_NAME     VARCHAR2(200)   NOT NULL,
    CREATED_BY      NUMBER(10)      NOT NULL,
    FILTER_JSON     CLOB,
    IS_SHARED       NUMBER(1)       DEFAULT 0 NOT NULL,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_SAVED_REPORTS PRIMARY KEY (REPORT_ID),
    CONSTRAINT FK_SR_USER FOREIGN KEY (CREATED_BY) REFERENCES USERS(USER_ID)
);

-- ----------------------------------------------------------------
-- INDEXES (performance-critical queries)
-- ----------------------------------------------------------------

CREATE INDEX IDX_REQUESTS_STATUS ON REQUESTS(STATUS);
CREATE INDEX IDX_REQUESTS_SUBMITTER ON REQUESTS(SUBMITTER_USER_ID);
CREATE INDEX IDX_REQUESTS_DIVISION ON REQUESTS(DIVISION_ID);
CREATE INDEX IDX_REQUESTS_TYPE ON REQUESTS(TYPE_ID);
CREATE INDEX IDX_REQUESTS_SLA ON REQUESTS(SLA_DEADLINE, IS_SLA_BREACHED);
CREATE INDEX IDX_REQUESTS_TECH ON REQUESTS(TECH_EXPERT_ID);
CREATE INDEX IDX_APPROVALS_REQUEST ON REQUEST_APPROVALS(REQUEST_ID, ACTION);
CREATE INDEX IDX_APPROVALS_APPROVER ON REQUEST_APPROVALS(APPROVER_USER_ID, ACTION);
CREATE INDEX IDX_TIMELINE_REQUEST ON REQUEST_TIMELINE(REQUEST_ID);
CREATE INDEX IDX_NOTIFS_USER ON NOTIFICATIONS(USER_ID, IS_READ);
CREATE INDEX IDX_USER_ROLES_USER ON USER_ROLES(USER_ID, IS_ACTIVE);
CREATE INDEX IDX_DELEGATIONS_ACTIVE ON ROLE_DELEGATIONS(DELEGATEE_USER_ID, ROLE_ID, IS_ACTIVE);
CREATE INDEX IDX_CONNECTIONS_USER ON CONNECTIONS(USER_ID);
CREATE INDEX IDX_CONNECTIONS_DIV ON CONNECTIONS(DIVISION_ID);
CREATE INDEX IDX_KB_PUBLISHED ON KB_ARTICLES(IS_PUBLISHED, CATEGORY_ID);
CREATE INDEX IDX_ANNOUNCEMENTS_ACTIVE ON ANNOUNCEMENTS(IS_ACTIVE, EXPIRES_AT);
CREATE INDEX IDX_TE_CATS_USER ON TECH_EXPERT_CATEGORIES(USER_ID, IS_ACTIVE);
CREATE INDEX IDX_FORM_FIELDS_TYPE ON FORM_FIELDS(TYPE_ID, IS_ACTIVE, SORT_ORDER);
