-- ============================================================
--  CRMP - 04_seed_data.sql
--  Core reference / seed data
-- ============================================================

-- ROLES
INSERT INTO ROLES (ROLE_ID, ROLE_CODE, ROLE_NAME, DESCRIPTION, SORT_ORDER)
VALUES (SEQ_ROLES.NEXTVAL, 'EMPLOYEE',      'Employee',          'Standard staff who raise service requests',                         1);
INSERT INTO ROLES (ROLE_ID, ROLE_CODE, ROLE_NAME, DESCRIPTION, SORT_ORDER)
VALUES (SEQ_ROLES.NEXTVAL, 'DIVISION_HEAD', 'Division Head',     'Approves requests at division level',                               2);
INSERT INTO ROLES (ROLE_ID, ROLE_CODE, ROLE_NAME, DESCRIPTION, SORT_ORDER)
VALUES (SEQ_ROLES.NEXTVAL, 'ISO',           'ISO Officer',       'Information Security Officer approval stage',                        3);
INSERT INTO ROLES (ROLE_ID, ROLE_CODE, ROLE_NAME, DESCRIPTION, SORT_ORDER)
VALUES (SEQ_ROLES.NEXTVAL, 'ADMIN_HR',      'Admin / HR',        'Administrative / HR approval stage',                                4);
INSERT INTO ROLES (ROLE_ID, ROLE_CODE, ROLE_NAME, DESCRIPTION, SORT_ORDER)
VALUES (SEQ_ROLES.NEXTVAL, 'DIRECTOR',      'Director',          'Director-level final approval stage',                               5);
INSERT INTO ROLES (ROLE_ID, ROLE_CODE, ROLE_NAME, DESCRIPTION, SORT_ORDER)
VALUES (SEQ_ROLES.NEXTVAL, 'TECH_EXPERT',   'Technical Expert',  'Resolves approved service requests',                                6);
INSERT INTO ROLES (ROLE_ID, ROLE_CODE, ROLE_NAME, DESCRIPTION, SORT_ORDER)
VALUES (SEQ_ROLES.NEXTVAL, 'MODERATOR',     'Moderator',         'Operational oversight for assigned service categories',             7);
INSERT INTO ROLES (ROLE_ID, ROLE_CODE, ROLE_NAME, DESCRIPTION, SORT_ORDER)
VALUES (SEQ_ROLES.NEXTVAL, 'OIC_IT',        'OIC IT',            'Organization-wide IT super administrator with full visibility',     8);

-- BUILDINGS
INSERT INTO BUILDINGS (BUILDING_ID, BUILDING_NAME, BUILDING_CODE) VALUES (SEQ_BUILDINGS.NEXTVAL, 'Main Block',          'MAIN');
INSERT INTO BUILDINGS (BUILDING_ID, BUILDING_NAME, BUILDING_CODE) VALUES (SEQ_BUILDINGS.NEXTVAL, 'Annexe A',            'ANXA');
INSERT INTO BUILDINGS (BUILDING_ID, BUILDING_NAME, BUILDING_CODE) VALUES (SEQ_BUILDINGS.NEXTVAL, 'Annexe B',            'ANXB');
INSERT INTO BUILDINGS (BUILDING_ID, BUILDING_NAME, BUILDING_CODE) VALUES (SEQ_BUILDINGS.NEXTVAL, 'Data Centre Block',   'DCB');

-- DIVISIONS
INSERT INTO DIVISIONS (DIVISION_ID, DIVISION_NAME, DIVISION_CODE) VALUES (SEQ_DIVISIONS.NEXTVAL, 'Information Technology', 'IT');
INSERT INTO DIVISIONS (DIVISION_ID, DIVISION_NAME, DIVISION_CODE) VALUES (SEQ_DIVISIONS.NEXTVAL, 'Human Resources',        'HR');
INSERT INTO DIVISIONS (DIVISION_ID, DIVISION_NAME, DIVISION_CODE) VALUES (SEQ_DIVISIONS.NEXTVAL, 'Finance',                'FIN');
INSERT INTO DIVISIONS (DIVISION_ID, DIVISION_NAME, DIVISION_CODE) VALUES (SEQ_DIVISIONS.NEXTVAL, 'Operations',             'OPS');
INSERT INTO DIVISIONS (DIVISION_ID, DIVISION_NAME, DIVISION_CODE) VALUES (SEQ_DIVISIONS.NEXTVAL, 'Procurement',            'PROC');
INSERT INTO DIVISIONS (DIVISION_ID, DIVISION_NAME, DIVISION_CODE) VALUES (SEQ_DIVISIONS.NEXTVAL, 'Administration',         'ADMIN');
INSERT INTO DIVISIONS (DIVISION_ID, DIVISION_NAME, DIVISION_CODE) VALUES (SEQ_DIVISIONS.NEXTVAL, 'Legal',                  'LEGAL');
INSERT INTO DIVISIONS (DIVISION_ID, DIVISION_NAME, DIVISION_CODE) VALUES (SEQ_DIVISIONS.NEXTVAL, 'Audit',                  'AUDIT');

-- SERVICE CATEGORIES
INSERT INTO SERVICE_CATEGORIES (CATEGORY_ID, CATEGORY_NAME, CATEGORY_CODE, DESCRIPTION, ICON_CLASS, COLOR_HEX, SORT_ORDER)
VALUES (SEQ_CATEGORIES.NEXTVAL, 'Hardware',         'HW',   'Physical hardware issues and requests',           'icon-cpu',     '#6366F1', 1);
INSERT INTO SERVICE_CATEGORIES (CATEGORY_ID, CATEGORY_NAME, CATEGORY_CODE, DESCRIPTION, ICON_CLASS, COLOR_HEX, SORT_ORDER)
VALUES (SEQ_CATEGORIES.NEXTVAL, 'Software',         'SW',   'Application and OS support requests',             'icon-monitor', '#8B5CF6', 2);
INSERT INTO SERVICE_CATEGORIES (CATEGORY_ID, CATEGORY_NAME, CATEGORY_CODE, DESCRIPTION, ICON_CLASS, COLOR_HEX, SORT_ORDER)
VALUES (SEQ_CATEGORIES.NEXTVAL, 'Network',          'NET',  'Network connectivity and infrastructure',         'icon-wifi',    '#06B6D4', 3);
INSERT INTO SERVICE_CATEGORIES (CATEGORY_ID, CATEGORY_NAME, CATEGORY_CODE, DESCRIPTION, ICON_CLASS, COLOR_HEX, SORT_ORDER)
VALUES (SEQ_CATEGORIES.NEXTVAL, 'Account Access',   'ACC',  'User account and access provisioning',            'icon-key',     '#10B981', 4);
INSERT INTO SERVICE_CATEGORIES (CATEGORY_ID, CATEGORY_NAME, CATEGORY_CODE, DESCRIPTION, ICON_CLASS, COLOR_HEX, SORT_ORDER)
VALUES (SEQ_CATEGORIES.NEXTVAL, 'Database',         'DB',   'Database modification and access requests',       'icon-database','#F59E0B', 5);
INSERT INTO SERVICE_CATEGORIES (CATEGORY_ID, CATEGORY_NAME, CATEGORY_CODE, DESCRIPTION, ICON_CLASS, COLOR_HEX, SORT_ORDER)
VALUES (SEQ_CATEGORIES.NEXTVAL, 'Telephony',        'TEL',  'Telephone and communication services',            'icon-phone',   '#EC4899', 6);
INSERT INTO SERVICE_CATEGORIES (CATEGORY_ID, CATEGORY_NAME, CATEGORY_CODE, DESCRIPTION, ICON_CLASS, COLOR_HEX, SORT_ORDER)
VALUES (SEQ_CATEGORIES.NEXTVAL, 'Internet',         'INT',  'Internet connection and bandwidth requests',      'icon-globe',   '#3B82F6', 7);
INSERT INTO SERVICE_CATEGORIES (CATEGORY_ID, CATEGORY_NAME, CATEGORY_CODE, DESCRIPTION, ICON_CLASS, COLOR_HEX, SORT_ORDER)
VALUES (SEQ_CATEGORIES.NEXTVAL, 'General IT',       'GIT',  'Miscellaneous IT service requests',               'icon-tool',    '#64748B', 8);

-- OPTION LISTS
INSERT INTO OPTION_LISTS (LIST_ID, LIST_NAME, LIST_CODE, DESCRIPTION) VALUES (SEQ_OPTION_LISTS.NEXTVAL, 'Priority Levels',     'PRIORITY',      'Standard priority levels');
INSERT INTO OPTION_LIST_VALUES (VALUE_ID, LIST_ID, VALUE_TEXT, VALUE_CODE, SORT_ORDER) VALUES (SEQ_OLV.NEXTVAL, 1, 'Low',    'LOW',    1);
INSERT INTO OPTION_LIST_VALUES (VALUE_ID, LIST_ID, VALUE_TEXT, VALUE_CODE, SORT_ORDER) VALUES (SEQ_OLV.NEXTVAL, 1, 'Normal', 'NORMAL', 2);
INSERT INTO OPTION_LIST_VALUES (VALUE_ID, LIST_ID, VALUE_TEXT, VALUE_CODE, SORT_ORDER) VALUES (SEQ_OLV.NEXTVAL, 1, 'High',   'HIGH',   3);
INSERT INTO OPTION_LIST_VALUES (VALUE_ID, LIST_ID, VALUE_TEXT, VALUE_CODE, SORT_ORDER) VALUES (SEQ_OLV.NEXTVAL, 1, 'Urgent', 'URGENT', 4);

INSERT INTO OPTION_LISTS (LIST_ID, LIST_NAME, LIST_CODE, DESCRIPTION) VALUES (SEQ_OPTION_LISTS.NEXTVAL, 'Operating Systems', 'OS_LIST', 'Supported operating systems');
INSERT INTO OPTION_LIST_VALUES (VALUE_ID, LIST_ID, VALUE_TEXT, VALUE_CODE, SORT_ORDER) VALUES (SEQ_OLV.NEXTVAL, 2, 'Windows 10',  'WIN10',   1);
INSERT INTO OPTION_LIST_VALUES (VALUE_ID, LIST_ID, VALUE_TEXT, VALUE_CODE, SORT_ORDER) VALUES (SEQ_OLV.NEXTVAL, 2, 'Windows 11',  'WIN11',   2);
INSERT INTO OPTION_LIST_VALUES (VALUE_ID, LIST_ID, VALUE_TEXT, VALUE_CODE, SORT_ORDER) VALUES (SEQ_OLV.NEXTVAL, 2, 'Linux',       'LINUX',   3);
INSERT INTO OPTION_LIST_VALUES (VALUE_ID, LIST_ID, VALUE_TEXT, VALUE_CODE, SORT_ORDER) VALUES (SEQ_OLV.NEXTVAL, 2, 'macOS',       'MACOS',   4);

INSERT INTO OPTION_LISTS (LIST_ID, LIST_NAME, LIST_CODE, DESCRIPTION) VALUES (SEQ_OPTION_LISTS.NEXTVAL, 'Connection Types', 'CONN_TYPES', 'Types of new connections');
INSERT INTO OPTION_LIST_VALUES (VALUE_ID, LIST_ID, VALUE_TEXT, VALUE_CODE, SORT_ORDER) VALUES (SEQ_OLV.NEXTVAL, 3, 'LAN',               'LAN',    1);
INSERT INTO OPTION_LIST_VALUES (VALUE_ID, LIST_ID, VALUE_TEXT, VALUE_CODE, SORT_ORDER) VALUES (SEQ_OLV.NEXTVAL, 3, 'Wi-Fi',             'WIFI',   2);
INSERT INTO OPTION_LIST_VALUES (VALUE_ID, LIST_ID, VALUE_TEXT, VALUE_CODE, SORT_ORDER) VALUES (SEQ_OLV.NEXTVAL, 3, 'Telephone Line',    'TEL',    3);
INSERT INTO OPTION_LIST_VALUES (VALUE_ID, LIST_ID, VALUE_TEXT, VALUE_CODE, SORT_ORDER) VALUES (SEQ_OLV.NEXTVAL, 3, 'Internet Leased',   'ILL',    4);
INSERT INTO OPTION_LIST_VALUES (VALUE_ID, LIST_ID, VALUE_TEXT, VALUE_CODE, SORT_ORDER) VALUES (SEQ_OLV.NEXTVAL, 3, 'VPN Access',        'VPN',    5);

-- WORKFLOWS
INSERT INTO WORKFLOWS (WORKFLOW_ID, WORKFLOW_NAME, DESCRIPTION, CREATED_BY)
VALUES (SEQ_WORKFLOWS.NEXTVAL, 'Standard 2-Stage',    '2-stage: Division Head + ISO',           NULL);
INSERT INTO WORKFLOWS (WORKFLOW_ID, WORKFLOW_NAME, DESCRIPTION, CREATED_BY)
VALUES (SEQ_WORKFLOWS.NEXTVAL, 'Full 3-Stage',        '3-stage: Division Head + Admin + Director', NULL);
INSERT INTO WORKFLOWS (WORKFLOW_ID, WORKFLOW_NAME, DESCRIPTION, CREATED_BY)
VALUES (SEQ_WORKFLOWS.NEXTVAL, 'Direct Resolution',   'No approval required — goes direct to tech pool', NULL);
INSERT INTO WORKFLOWS (WORKFLOW_ID, WORKFLOW_NAME, DESCRIPTION, CREATED_BY)
VALUES (SEQ_WORKFLOWS.NEXTVAL, 'Connection Request',  '3-stage: Division Head + ISO + Director',  NULL);

-- WORKFLOW STAGES
-- Workflow 1: Standard 2-Stage
INSERT INTO WORKFLOW_STAGES (STAGE_ID, WORKFLOW_ID, STAGE_ORDER, STAGE_NAME, ROLE_ID, IS_CONFIRMATION_ONLY, REMARKS_REQUIRED)
VALUES (SEQ_WF_STAGES.NEXTVAL, 1, 1, 'Division Head Approval', 2, 0, 1);
INSERT INTO WORKFLOW_STAGES (STAGE_ID, WORKFLOW_ID, STAGE_ORDER, STAGE_NAME, ROLE_ID, IS_CONFIRMATION_ONLY, REMARKS_REQUIRED)
VALUES (SEQ_WF_STAGES.NEXTVAL, 1, 2, 'ISO Verification',       3, 1, 0);
-- Workflow 2: Full 3-Stage
INSERT INTO WORKFLOW_STAGES (STAGE_ID, WORKFLOW_ID, STAGE_ORDER, STAGE_NAME, ROLE_ID, IS_CONFIRMATION_ONLY, REMARKS_REQUIRED)
VALUES (SEQ_WF_STAGES.NEXTVAL, 2, 1, 'Division Head Approval', 2, 0, 1);
INSERT INTO WORKFLOW_STAGES (STAGE_ID, WORKFLOW_ID, STAGE_ORDER, STAGE_NAME, ROLE_ID, IS_CONFIRMATION_ONLY, REMARKS_REQUIRED)
VALUES (SEQ_WF_STAGES.NEXTVAL, 2, 2, 'Admin / HR Review',      4, 0, 1);
INSERT INTO WORKFLOW_STAGES (STAGE_ID, WORKFLOW_ID, STAGE_ORDER, STAGE_NAME, ROLE_ID, IS_CONFIRMATION_ONLY, REMARKS_REQUIRED)
VALUES (SEQ_WF_STAGES.NEXTVAL, 2, 3, 'Director Sanction',      5, 0, 1);
-- Workflow 4: Connection Request
INSERT INTO WORKFLOW_STAGES (STAGE_ID, WORKFLOW_ID, STAGE_ORDER, STAGE_NAME, ROLE_ID, IS_CONFIRMATION_ONLY, REMARKS_REQUIRED)
VALUES (SEQ_WF_STAGES.NEXTVAL, 4, 1, 'Division Head Approval', 2, 0, 1);
INSERT INTO WORKFLOW_STAGES (STAGE_ID, WORKFLOW_ID, STAGE_ORDER, STAGE_NAME, ROLE_ID, IS_CONFIRMATION_ONLY, REMARKS_REQUIRED)
VALUES (SEQ_WF_STAGES.NEXTVAL, 4, 2, 'ISO Security Review',    3, 0, 1);
INSERT INTO WORKFLOW_STAGES (STAGE_ID, WORKFLOW_ID, STAGE_ORDER, STAGE_NAME, ROLE_ID, IS_CONFIRMATION_ONLY, REMARKS_REQUIRED)
VALUES (SEQ_WF_STAGES.NEXTVAL, 4, 3, 'Director Sanction',      5, 0, 1);

-- REQUEST TYPES with workflows
INSERT INTO REQUEST_TYPES (TYPE_ID, CATEGORY_ID, TYPE_NAME, TYPE_CODE, DESCRIPTION, SLA_HOURS, WORKFLOW_ID, ICON_CLASS, IS_CONNECTION_TYPE)
VALUES (SEQ_REQUEST_TYPES.NEXTVAL, 1, 'Hardware Repair',       'HW_REPAIR',    'Request repair of existing hardware',             48,  1, 'icon-tool',       0);
INSERT INTO REQUEST_TYPES (TYPE_ID, CATEGORY_ID, TYPE_NAME, TYPE_CODE, DESCRIPTION, SLA_HOURS, WORKFLOW_ID, ICON_CLASS, IS_CONNECTION_TYPE)
VALUES (SEQ_REQUEST_TYPES.NEXTVAL, 1, 'New Hardware Request',  'HW_NEW',       'Request procurement of new hardware',             120, 2, 'icon-package',    0);
INSERT INTO REQUEST_TYPES (TYPE_ID, CATEGORY_ID, TYPE_NAME, TYPE_CODE, DESCRIPTION, SLA_HOURS, WORKFLOW_ID, ICON_CLASS, IS_CONNECTION_TYPE)
VALUES (SEQ_REQUEST_TYPES.NEXTVAL, 2, 'Software Installation', 'SW_INSTALL',   'Request installation of licensed software',       24,  1, 'icon-download',   0);
INSERT INTO REQUEST_TYPES (TYPE_ID, CATEGORY_ID, TYPE_NAME, TYPE_CODE, DESCRIPTION, SLA_HOURS, WORKFLOW_ID, ICON_CLASS, IS_CONNECTION_TYPE)
VALUES (SEQ_REQUEST_TYPES.NEXTVAL, 2, 'Software Issue',        'SW_ISSUE',     'Report a software bug or malfunction',            24,  3, 'icon-alert',      0);
INSERT INTO REQUEST_TYPES (TYPE_ID, CATEGORY_ID, TYPE_NAME, TYPE_CODE, DESCRIPTION, SLA_HOURS, WORKFLOW_ID, ICON_CLASS, IS_CONNECTION_TYPE)
VALUES (SEQ_REQUEST_TYPES.NEXTVAL, 3, 'New Network Connection','NET_NEW',       'Request a new LAN/Wi-Fi connection',              96,  4, 'icon-wifi',       1);
INSERT INTO REQUEST_TYPES (TYPE_ID, CATEGORY_ID, TYPE_NAME, TYPE_CODE, DESCRIPTION, SLA_HOURS, WORKFLOW_ID, ICON_CLASS, IS_CONNECTION_TYPE)
VALUES (SEQ_REQUEST_TYPES.NEXTVAL, 3, 'Network Fault',         'NET_FAULT',    'Report a network outage or connectivity issue',   8,   3, 'icon-alert-tri',  0);
INSERT INTO REQUEST_TYPES (TYPE_ID, CATEGORY_ID, TYPE_NAME, TYPE_CODE, DESCRIPTION, SLA_HOURS, WORKFLOW_ID, ICON_CLASS, IS_CONNECTION_TYPE)
VALUES (SEQ_REQUEST_TYPES.NEXTVAL, 4, 'Account Creation',      'ACC_CREATE',   'Request creation of a new user account',          48,  2, 'icon-user-plus',  0);
INSERT INTO REQUEST_TYPES (TYPE_ID, CATEGORY_ID, TYPE_NAME, TYPE_CODE, DESCRIPTION, SLA_HOURS, WORKFLOW_ID, ICON_CLASS, IS_CONNECTION_TYPE)
VALUES (SEQ_REQUEST_TYPES.NEXTVAL, 4, 'Password Reset',        'ACC_RESET',    'Request password reset for an account',           4,   3, 'icon-lock',       0);
INSERT INTO REQUEST_TYPES (TYPE_ID, CATEGORY_ID, TYPE_NAME, TYPE_CODE, DESCRIPTION, SLA_HOURS, WORKFLOW_ID, ICON_CLASS, IS_CONNECTION_TYPE)
VALUES (SEQ_REQUEST_TYPES.NEXTVAL, 5, 'Database Modification', 'DB_MOD',       'Request data modification in a database',         72,  2, 'icon-database',   0);
INSERT INTO REQUEST_TYPES (TYPE_ID, CATEGORY_ID, TYPE_NAME, TYPE_CODE, DESCRIPTION, SLA_HOURS, WORKFLOW_ID, ICON_CLASS, IS_CONNECTION_TYPE)
VALUES (SEQ_REQUEST_TYPES.NEXTVAL, 6, 'New Telephone Line',    'TEL_NEW',      'Request installation of a new telephone line',    96,  4, 'icon-phone',      1);
INSERT INTO REQUEST_TYPES (TYPE_ID, CATEGORY_ID, TYPE_NAME, TYPE_CODE, DESCRIPTION, SLA_HOURS, WORKFLOW_ID, ICON_CLASS, IS_CONNECTION_TYPE)
VALUES (SEQ_REQUEST_TYPES.NEXTVAL, 7, 'Internet Connection',   'INT_NEW',      'Request new internet/leased line connection',     120, 4, 'icon-globe',      1);

-- SLA CONFIGS (global defaults, can be overridden per type)
INSERT INTO SLA_CONFIGS (SLA_ID, TYPE_ID, PRIORITY, SLA_HOURS, WARN_THRESHOLD_PCT, BREACH_NOTIFY_ROLES)
VALUES (SEQ_SLA_CONFIGS.NEXTVAL, NULL, 'URGENT', 4,   75, 'MODERATOR,OIC_IT');
INSERT INTO SLA_CONFIGS (SLA_ID, TYPE_ID, PRIORITY, SLA_HOURS, WARN_THRESHOLD_PCT, BREACH_NOTIFY_ROLES)
VALUES (SEQ_SLA_CONFIGS.NEXTVAL, NULL, 'HIGH',   24,  75, 'MODERATOR,OIC_IT');
INSERT INTO SLA_CONFIGS (SLA_ID, TYPE_ID, PRIORITY, SLA_HOURS, WARN_THRESHOLD_PCT, BREACH_NOTIFY_ROLES)
VALUES (SEQ_SLA_CONFIGS.NEXTVAL, NULL, 'NORMAL', 72,  75, 'MODERATOR');
INSERT INTO SLA_CONFIGS (SLA_ID, TYPE_ID, PRIORITY, SLA_HOURS, WARN_THRESHOLD_PCT, BREACH_NOTIFY_ROLES)
VALUES (SEQ_SLA_CONFIGS.NEXTVAL, NULL, 'LOW',    168, 80, 'MODERATOR');

COMMIT;
